### ISSUE TITLE
msp430emulator.com is down again

### ISSUE THREAD

**Issue by torokati44** [RudolfGeosits/MSP430-Emulator#10]
Are the client side sources not available anywhere else, so we can run the whole thing locally?

**Comment by RudolfGeosits** [comment]
My apologies for my website being down. Please see that it should now be available for use. The reason for the common interruption is that my server has been automatically stopping at the end of the month. I must reconfigure that server and move my emulation service. This is on my to-do list now.

Unfortunately, the client side source is not available at this time. I may be coming back to continue this project shortly. Thanks for your patience and happy hacking!

**Comment by vi** [comment]
> It's not just you! msp430emulator.com is down.
