### ISSUE TITLE
How to give digital inputs via ports?

### ISSUE THREAD

**Issue by zekeriyasari** [RudolfGeosits/MSP430-Emulator#11]
While using the emulator online, I could not give inputs to the microcontroller via S2 pushbutton on the launchpad. I could not find any interface to give digital inputs via the ports. Am I missing something?

**Comment by RudolfGeosits** [comment]
Yes, I am aware of this issue; I'm re-writing the online emulation platform in my spare time right now. The ability to give inputs to the simulation is still in progress, please support the project if you'd like to see the simulator completed!
