### ISSUE TITLE
Emulator online but not working

### ISSUE THREAD

**Issue by canchebagur** [RudolfGeosits/MSP430-Emulator#16]
@RudolfGeosits I just found this tool and I think is great. Unfortunately, I can't run either the examples provided here or the code I am compiling by myself. Is the tool online but not working or I am missing something? What is the process for running the examples or compiled code? 

Thanks for the answer!

**Comment by tingox** [comment]
I can confirm that the online version is not working, neither in Chrome nor in Edge (on win10). I have not tried a local version

**Comment by RudolfGeosits** [comment]
@canchebagur @tingox As there is some renewed interest, the simulator is back up and running at https://msp430.online/ if you have specific things you're trying to accomplish by using a software model of the TI please contact us : )

![image](https://user-images.githubusercontent.com/7827544/181728434-143dd0ba-702b-421e-ae9a-36f25f4e36dd.png)

**Comment by tingox** [comment]
Thank you. I can confirm that it now works, both in Firefox and chromium,

**Comment by RudolfGeosits** [comment]
> Thank you. I can confirm that it now works, both in Firefox and chromium,

Great, firefox must have fixed some of the issues we were having a while back then. Enjoy.

**Comment by rajeshjoshi8792** [comment]
i m facing same issue as @canchebagur. i tried in chrome, safari and firefox. but its not working.

**Comment by RudolfGeosits** [comment]
Raj,

Please try again now I have updated the site.

-Rudolf
________________________________
